
include: package:flutter_lints/flutter.yaml

linter:
    rules:
       unawaited_futures: true
       omit_local_variables_types: ignore
       await_only_futures: true
       camel_case_types: true
       cancel_subscriptions: true
       comment_references: true


analyzer:
    strong-mode:
        implicit-casts: false
        implicit-dynamic: false
