name: jovial_widgets
description: Miscellaneous Dart widgets
version: 0.0.1
homepage: https://bill.jovial.com/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

repository: https://github.com/zathras/misc/tree/master/dart/jovial_widgets
