name: jovial_misc
description: Miscellaneous Dart libraries, including interoperability with java.io.DataInputStream and java.io.DataOutputStream.
version: 0.4.2
homepage: https://bill.jovial.com/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
    pointycastle: ^1.0.2
    intl: ^0.16.0
    async: ^2.4.0
    collection: ^1.14.11
    convert: ^2.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

repository: https://github.com/zathras/misc/tree/master/dart/jovial_misc
