name: jovial_misc
description: Miscellaneous Dart libraries
# version: 0.0.1
# homepage: https://github.com/zathras/misc

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
    pointycastle: ^1.0.2
    intl: ^0.16.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
