name: jovial_misc
description: Miscellaneous Dart libraries, including interoperability with java.io.DataInputStream and java.io.DataOutputStream.
version: 0.5.0
homepage: https://bill.jovial.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
    pointycastle: ^3.0.0-nullsafety.2
    intl: ^0.17.0
    async: ^2.5.0
    collection: ^1.14.11
    convert: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.6

repository: https://github.com/zathras/misc/tree/master/dart/jovial_misc
